# Generated by Django 2.0.1 on 2018-01-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_test',
            new_name='post_text',
        ),
    ]
